# Generated by Django 4.1.2 on 2022-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='name', default=None, max_length=16, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=256, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=8, verbose_name='性别'),
        ),
    ]
